name: car-price-predection
channels:
 what the `environment.yml` file might look like for a Python project:

```yaml
name: base
channels:
  - defaults
dependencies:
  - python=3.10
  - flake8
  - pytest
  - any-other-dependencies
